### ISSUE TITLE
CSV/JSON Bulk Importer

### ISSUE THREAD

**Issue by pudo** [CodeForAfrica/grano#17]
Have a simple mapping format, e.g.:

``` yaml
source_url: http://...
mapping:
  - column: person_a
    element: source
    schema: base
    attribute: name
  - column: person_b
    element: target
    schema: base
    attribute: name
  - column: relation_description
    element: relation
    schema: my_schema
    attribute: description
```

Sub-tasks:
- [x] pipeline model for data process logging
- [x] implement an importer
- [ ] make a command-line tool
- [ ] document the mapping format.
