### ISSUE TITLE
Can't define multiple entities/relationships on a single YAML file

### ISSUE THREAD

**Issue by jazzido** [CodeForAfrica/grano#27]
It'd be nice to be able to do something like this, instead of having to create a separate file for each entity or relation type.

``` yaml
- name: person
  label: A person
  obj: entity
  hidden: no
  attributes:
    - name: first_name
      label: First name
    - name: last_name
      label: Last name
    - name: title
      label: Title
      hidden: yes

- name: gift
  label: A present
  label_in: Gifts received
  label_out: Gifts given
  obj: relation
  attributes:
    - name: description
      label: Description
    - name: value
      label: Value (in EUR)

```
