### ISSUE TITLE
Entity types: best practice?

### ISSUE THREAD

**Issue by jazzido** [CodeForAfrica/grano#32]
Suppose I'm working with this schema:

```
- name: fellow
  label: An OpenNews fellow
  obj: entity
  hidden: no
  attributes:
    - name: twitter_handle
      label: Twitter handle

- name: news_organization
  label: A news organization
  obj: entity
  hidden: no
  attributes:
    - name: url
      label: URL

- name: fellowship
  label: A Fellowship
  label_in: Was hosted by
  label_out: Worked for
  obj: relation
  attributes:
    - name: start_date
      label: Start date
    - name: end_date
      label: End date
```

That defines a bipartite graph (two clases of vertices). How would I use `grano-client` to get all the "fellows" or the "news organizations"? In other words, is it possible to get the schema that a given properties was defined in?
