### ISSUE TITLE
Attribute validation

### ISSUE THREAD

**Issue by jazzido** [CodeForAfrica/grano#36]
Something along these lines:

``` yaml
- name: organizacion
  label: Una organizacion
  obj: entity
  hidden: no
  attributes:
    - name: nombre
      label: Nombre
      required: true
    - name: date
      label: Date
      pattern: \d\d\d\d-\d\d-\d\d
```
