### ISSUE TITLE
Feature Request: datatype `enum`

### ISSUE THREAD

**Issue by jazzido** [CodeForAfrica/grano#47]
It would look like this: 

``` yaml
    - name: person_id_type
      label: ID Type
      datatype: ['foo', 'bar', 'quux']::tuple
```

Not sure about the possible values syntax. What do you think?
